version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql
      DB_USER: faceuser
      DB_PASSWORD: facepass
      DB_NAME: detection_face_db
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: detection_face_db
      MYSQL_USER: faceuser
      MYSQL_PASSWORD: facepass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: